name:                advent-of-code
version:             0.1.0.0
github:              "githubuser/advent-of-code"
license:             BSD3
author:              "hstk"
maintainer:          "example@example.com"
copyright:           "2018 hstk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- criterion
- parallel
- raw-strings-qq
- time
- transformers
- trifecta
- vector
- split

executables:
  lumber-exe:
    main:                "day18\\Lumber.hs"
    source-dirs:         "2018"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -main-is Lumber
    dependencies:
    - advent-of-code

library:
  source-dirs: 
  - "2017"
  - "2018"
  # ghc-options:
  # - -XQuasiQuotes
